import { NextResponse } from "next/server";

interface Prestador {
  prestNome: string;
  prestEndereco: string;
  prestNumero: string;
  prestComplemento: string;
  prestBairro: string;
  prestCEP: string;
  telefone1: string;
  telefone2: string;
  telefone3: string;
}

const prestadores: Prestador[] = [
  {
    prestNome: "HOSPITAL E MATER NOSSA SRA ROSARIO",
    prestEndereco: "R. DOUTOR EDSON DE MELO",
    prestNumero: "357",
    prestComplemento: "",
    prestBairro: "VILA MARIA ALTA",
    prestCEP: "02122080",
    telefone1: "1140901740",
    telefone2: "",
    telefone3: "",
  },
  {
    prestNome: "HOSPITAL SAO BERNARDO",
    prestEndereco: "AV. LUCAS NOGUEIRA GARCEZ",
    prestNumero: "400",
    prestComplemento: "ANEXO R MARMARA N161 E",
    prestBairro: "CENTRO",
    prestCEP: "09750660",
    telefone1: "1140901740",
    telefone2: "40901740",
    telefone3: "31552000",
  },
  {
    prestNome: "LAVOISIER MEDICINA DIAGNOSTICA - BELA VISTA",
    prestEndereco: "AV ANTONIO CARLOS COSTA",
    prestNumero: "696",
    prestComplemento: "",
    prestBairro: "BELA VISTA",
    prestCEP: "113047-4488",
    telefone1: "40023633",
    telefone2: "",
    telefone3: "",
  },
  {
    prestNome: "HOSPITAL BOSQUE DA SAUDE",
    prestEndereco: "AV BOSQUE DA SAUDE",
    prestNumero: "1922",
    prestComplemento: "/ 1926",
    prestBairro: "SAUDE",
    prestCEP: "04142082",
    telefone1: "",
    telefone2: "",
    telefone3: "",
  },{
    prestNome: "EINSTEN IMAGENS MEDS LTDA",
    prestEndereco: "AV CONS NEBIAS",
    prestNumero: "741",
    prestComplemento: "",
    prestBairro: "BOQUEIRAO",
    prestCEP: "11045003",
    telefone1: "",
    telefone2: "",
    telefone3: "",
  },{
    prestNome: "FISIOMED FISIOTERAPIA ESPECIAL",
    prestEndereco: "R. SAO PAULO",
    prestNumero: "2296",
    prestComplemento: "",
    prestBairro: "SANTA PAULA",
    prestCEP: "09541100",
    telefone1: "1142278230",
    telefone2: "42278230",
    telefone3: "",
  },{
    prestNome: "CLINICA SAINT NICHOLAS LTDA - SUZANO",
    prestEndereco: "R. VINTE E SETE DE OUTUBRO",
    prestNumero: "106",
    prestComplemento: "",
    prestBairro: "JARDIM SUELY",
    prestCEP: "08674200",
    telefone1: "1147467800",
    telefone2: "",
    telefone3: "",
  },{
    prestNome: "HOSPITAL SALVALUS",
    prestEndereco: "R. BRESSER",
    prestNumero: "1954",
    prestComplemento: "",
    prestBairro: "MOOCA",
    prestCEP: "03164160",
    telefone1: "1140901740",
    telefone2: "",
    telefone3: "",
  },{
    prestNome: "NOTRELABS OSASCO - AUTONOMISTAS",
    prestEndereco: "AV. DOS AUTONOMISTAS",
    prestNumero: "2511",
    prestComplemento: "2515",
    prestBairro: "CENTRO",
    prestCEP: "06090020",
    telefone1: "1140901740",
    telefone2: "31552000",
    telefone3: "",
  },{
    prestNome: "NOTRELABS OSASCO ITABUNA",
    prestEndereco: "R. ITABUNA",
    prestNumero: "76",
    prestComplemento: "ANEXO 84",
    prestBairro: "CENTRO",
    prestCEP: "06010120",
    telefone1: "1140901740",
    telefone2: "31552000",
    telefone3: "",
  },
  {
    prestNome: "ALBANOS FONOAUDIOLOGIA INTEGRA",
    prestEndereco: "AV. WASHINGTON LUIS",
    prestNumero: "1930",
    prestComplemento: "",
    prestBairro: "SANTO AMARO",
    prestCEP: "04662002",
    telefone1: "1126152720",
    telefone2: "26152720",
    telefone3: "",
  },{
    prestNome: "HPS UNIDADE INTERNACAO",
    prestEndereco: "R. SAO LAZARO",
    prestNumero: "15",
    prestComplemento: "",
    prestBairro: "JARDIM BRASIL",
    prestCEP: "13209220",
    telefone1: "1145216438",
    telefone2: "45216438",
    telefone3: "",
  },{
    prestNome: "CLGS ASSESSORIA EM SAUDE LTDA",
    prestEndereco: "R. DOUTOR RAMOS DE AZEVEDO",
    prestNumero: "50",
    prestComplemento: "CASA 1",
    prestBairro: "CENTRO",
    prestCEP: "07012020",
    telefone1: "1137457636",
    telefone2: "37457636",
    telefone3: "",
  },{
    prestNome: "FISIO SBC CLIN DE FISIOT LTDA",
    prestEndereco: "R. CORAL",
    prestNumero: "159",
    prestComplemento: "",
    prestBairro: "JARDIM DAS AMERICAS",
    prestCEP: "09725650",
    telefone1: "1132424924",
    telefone2: "96472891",
    telefone3: "",
  },{
    prestNome: "CEDECO CTO DE ESPEC EM DIAG SC",
    prestEndereco: "R. NOVE DE JULHO",
    prestNumero: "31",
    prestComplemento: "",
    prestBairro: "CENTRO",
    prestCEP: "08674230",
    telefone1: "1147465686",
    telefone2: "",
    telefone3: "",
  },{
    prestNome: "CENTRO PAULISTA DE PSICOLOGIA",
    prestEndereco: "R. ORENSE",
    prestNumero: "41",
    prestComplemento: "",
    prestBairro: "CENTRO",
    prestCEP: "09920650",
    telefone1: "1137171987",
    telefone2: "11973112798",
    telefone3: "",
  },{
    prestNome: "MULTIPSICO CLIN DE PSICOLOGIA",
    prestEndereco: "R CAMPOS SALES",
    prestNumero: "596",
    prestComplemento: "",
    prestBairro: "CENTRO",
    prestCEP: "",
    telefone1: "1127593798",
    telefone2: "11997171503",
    telefone3: "",
},
{
    prestNome: "AVANTE MEDICINA DIAG EIRELI",
    prestEndereco: "R. DOUTOR RAUL DA ROCHA MEDEIROS",
    prestNumero: "62",
    prestComplemento: "",
    prestBairro: "TATUAPE",
    prestCEP: "03071100",
    telefone1: "1120902626",
    telefone2: "50314557",
    telefone3: "",
},
{
    prestNome: "BIOFISIO C I FISIOTERAPIA LTDA",
    prestEndereco: "AV. ESPERANCA",
    prestNumero: "700",
    prestComplemento: "",
    prestBairro: "CENTRO",
    prestCEP: "07095005",
    telefone1: "1124681675",
    telefone2: "11947229478",
    telefone3: "",
},
{
    prestNome: "HOSPITAL E MATERNIDADE MODELO",
    prestEndereco: "R. AFONSO PEDRAZZI",
    prestNumero: "180",
    prestComplemento: "",
    prestBairro: "VILA TRUJILLO",
    prestCEP: "18060450",
    telefone1: "1540901740",
    telefone2: "1532127600",
    telefone3: "",
},
{
    prestNome: "PRAXIS MEDICINA ESPECIALIZADA E REABILITACAO LTDA",
    prestEndereco: "R. BENEDITO CAMARGO SANTOS",
    prestNumero: "239",
    prestComplemento: "",
    prestBairro: "VILA TRUJILLO",
    prestCEP: "18060440",
    telefone1: "1533261488",
    telefone2: "159963035",
    telefone3: "",
},
{
    prestNome: "CLINICA MEDICA SERRA LTDA",
    prestEndereco: "R. LORD COCKRANE",
    prestNumero: "616",
    prestComplemento: "",
    prestBairro: "IPIRANGA",
    prestCEP: "04213001",
    telefone1: "11989588458",
    telefone2: "32522559",
    telefone3: "",
},
{
    prestNome: "CC AUTONOMISTAS",
    prestEndereco: "AV. DOS AUTONOMISTAS",
    prestNumero: "2602",
    prestComplemento: "2606",
    prestBairro: "CENTRO",
    prestCEP: "0609001",
    telefone1: "1140901740",
    telefone2: "31472100",
    telefone3: "",
},
{
    prestNome: "PA BARRA FUNDA",
    prestEndereco: "AV. FRANCISCO MATARAZZO",
    prestNumero: "612",
    prestComplemento: "ANEXO 628",
    prestBairro: "AGUA BRANCA",
    prestCEP: "05001000",
    telefone1: "31552000",
    telefone2: "1140901740",
    telefone3: "",
},
{
    prestNome: "NOTRELABS ANGELICA",
    prestEndereco: "AV. ANGELICA",
    prestNumero: "1045",
    prestComplemento: "",
    prestBairro: "HIGIENOPOLIS",
    prestCEP: "01227100",
    telefone1: "1140901740",
    telefone2: "31552000",
    telefone3: "",
},
{
    prestNome: "TRANSDUSON MEDICOS ASSOCIADOS LTDA",
    prestEndereco: "AV CORIFEU DE AZEVEDO MARQUES",
    prestNumero: "209",
    prestComplemento: "",
    prestBairro: "CENTRO",
    prestCEP: "06320090",
    telefone1: "1141858595",
    telefone2: "114185859",
    telefone3: "",
},{
  prestNome: "HOSPITAL RENASCENCA CAMPINAS",
  prestEndereco: "AV. BARAO DE ITAPURA",
  prestNumero: "1444",
  prestComplemento: "//1378 RUA TIRADENTES 457/463",
  prestBairro: "BOTAFOGO",
  prestCEP: "13020432",
  telefone1: "1940901740",
  telefone2: "31552000",
  telefone3: "",
},
{
  prestNome: "PSICOBLUE PSICOLOGIA E FONOAUD",
  prestEndereco: "R. RETIRO GRANDE",
  prestNumero: "101",
  prestComplemento: "CONJ 11 12 E 13",
  prestBairro: "CIDADE MAE DO CEU",
  prestCEP: "03306040",
  telefone1: "11992596788",
  telefone2: "1122279666",
  telefone3: "",
},
{
  prestNome: "INST VIDA DE FISIOT S C LTDA",
  prestEndereco: "R. ELOY CANDIDO LOPES",
  prestNumero: "137",
  prestComplemento: "",
  prestBairro: "CENTRO",
  prestCEP: "06010130",
  telefone1: "1144276121",
  telefone2: "975446165",
  telefone3: "",
},
{
  prestNome: "LABORATORIO DELIBERATO DE ANALISES CLINICAS LTDA",
  prestEndereco: "R. VEREADOR JOSE BARBOSA DE ARAUJO",
  prestNumero: "89",
  prestComplemento: "",
  prestBairro: "VILA VIRGINIA",
  prestCEP: "08573040",
  telefone1: "1126303000",
  telefone2: "1146562739",
  telefone3: "",
},
{
  prestNome: "HOSPITAL E MATERNIDADE DE GUARULHOS",
  prestEndereco: "AV. TIRADENTES",
  prestNumero: "1015",
  prestComplemento: "1.037 LOTE 1 AO 16",
  prestBairro: "JARDIM GUARULHOS",
  prestCEP: "07090000",
  telefone1: "1140901740",
  telefone2: "",
  telefone3: "",
},
{
  prestNome: "CENTRO MED ALFA LTDA",
  prestEndereco: "R. ORATORIO",
  prestNumero: "1260",
  prestComplemento: "",
  prestBairro: "BANGU",
  prestCEP: "09280550",
  telefone1: "",
  telefone2: "",
  telefone3: "",
},
{
  prestNome: "HOSPITAL VERA CRUZ",
  prestEndereco: "AV. ANDRADE NEVES",
  prestNumero: "402",
  prestComplemento: "",
  prestBairro: "CENTRO",
  prestCEP: "CAMPINAS - SP",
  telefone1: "1937943221",
  telefone2: "",
  telefone3: "",
},
{
  prestNome: "HOSPITAL FREI GALVÃO SANTOS",
  prestEndereco: "R. DOUTOR HEITOR DE MORAES",
  prestNumero: "19",
  prestComplemento: "",
  prestBairro: "SANTOS",
  prestCEP: "",
  telefone1: "",
  telefone2: "",
  telefone3: "",
},
{
  prestNome: "HOSPITAL CRUZEIRO DO SUL",
  prestEndereco: "AV. DOS AUTONOMISTAS",
  prestNumero: "2502",
  prestComplemento: "",
  prestBairro: "CENTRO",
  prestCEP: "06090010",
  telefone1: "",
  telefone2: "",
  telefone3: "",
},
{
  prestNome: "HOSPITAL FAMILY",
  prestEndereco: "RUA JOAO SANTUCCI",
  prestNumero: "250",
  prestComplemento: "ANEXO A",
  prestBairro: "TABOAO DA SERRA",
  prestCEP: "",
  telefone1: "",
  telefone2: "",
  telefone3: "",
},{
  prestNome: "NOTRELABS SANTO AMARO",
  prestEndereco: "R. SAO JOSE",
  prestNumero: "49",
  prestComplemento: "1037 LOTE 1 AO 16",
  prestBairro: "SANTO AMARO",
  prestCEP: "04739000",
  telefone1: "1140901740",
  telefone2: "31552000",
  telefone3: "",
},
{
  prestNome: "NOTRELABS MAUA GENERAL OSORIO",
  prestEndereco: "R. GENERAL OSORIO",
  prestNumero: "228",
  prestComplemento: "",
  prestBairro: "VILA BOCAINA",
  prestCEP: "09310050",
  telefone1: "1140901740",
  telefone2: "31552000",
  telefone3: "",
},
{
  prestNome: "NOTRELABS TATUAPE ICEM",
  prestEndereco: "R. ICEM",
  prestNumero: "57",
  prestComplemento: "",
  prestBairro: "CIDADE MAE DO CEU",
  prestCEP: "03306020",
  telefone1: "1140901740",
  telefone2: "",
  telefone3: "",
},
{
  prestNome: "NOTRELABS SANTO ANDRE",
  prestEndereco: " AV. QUINZE DE NOVEMBRO",
  prestNumero: "512",
  prestComplemento: "ANEXO 544",
  prestBairro: "CENTRO",
  prestCEP: "09015000",
  telefone1: "1140901740",
  telefone2: "",
  telefone3: "",
},
{
  prestNome: "NOTRELABS IPIRANGA",
  prestEndereco: "AV. DOUTOR GENTIL DE MOURA",
  prestNumero: "412",
  prestComplemento: "",
  prestBairro: "IPIRANGA",
  prestCEP: "04278000",
  telefone1: "1140901740",
  telefone2: "",
  telefone3: "",
},
{
  prestNome: " QUALIVIDA ANGELICA",
  prestEndereco: "QUALIVIDA ANGELICA",
  prestNumero: "381",
  prestComplemento: "",
  prestBairro: "SANTA CECILIA",
  prestCEP: "01227000",
  telefone1: "1140901740",
  telefone2: "31551878",
  telefone3: "",
},
{
  prestNome: "NOTRELABS SBC ATLANTICA",
  prestEndereco: "R. ATLANTICA",
  prestNumero: "107",
  prestComplemento: "ANEXO 121 E 135",
  prestBairro: "JARDIM DO MAR",
  prestCEP: "",
  telefone1: "1140901740",
  telefone2: "",
  telefone3: "",
},
{
  prestNome: "NOTRELABS GUARULHOS",
  prestEndereco: "AV PAULO FACCINI",
  prestNumero: "96",
  prestComplemento: "",
  prestBairro: "MACEDO",
  prestCEP: "",
  telefone1: "",
  telefone2: "",
  telefone3: "",
},
{
  prestNome: "HOSPITAL PAULO SACRAMENTO",
  prestEndereco: "R. QUINZE DE NOVEMBRO",
  prestNumero: "865",
  prestComplemento: "",
  prestBairro: "CENTRO",
  prestCEP: "",
  telefone1: "",
  telefone2: "",
  telefone3: "",
},
{
  prestNome: "HOSPITAL SANTANA MOGI",
  prestEndereco: "R. DOUTOR OSMAR MARINHO COUTO",
  prestNumero: "71",
  prestComplemento: "",
  prestBairro: "CENTRO",
  prestCEP: "08730500",
  telefone1: "1140901740",
  telefone2: "",
  telefone3: "",
},
{
  prestNome: "HSCOR - HOSPITAL DO CORACAO RJ",
  prestEndereco: "R GENERAL MITRE",
  prestNumero: "",
  prestComplemento: "110 115 142",
  prestBairro: "JARDIM 25 DE AGOSTO",
  prestCEP: "",
  telefone1: "",
  telefone2: "",
  telefone3: "",
},{
  prestNome: "HOSPITAL NOTRECARE SOROCABA",
  prestEndereco: "R RODRIGUES PACHECO",
  prestNumero: "145",
  prestComplemento: "",
  prestBairro: "",
  prestCEP: "",
  telefone1: "",
  telefone2: "",
  telefone3: "",
},{
  prestNome: "PA MOGI",
  prestEndereco: "R ENGENHEIRO EUGENIO MOTTA",
  prestNumero: "255",
  prestComplemento: "",
  prestBairro: "CENTRO",
  prestCEP: "",
  telefone1: "",
  telefone2: "",
  telefone3: "",
},{
  prestNome: "CASA DE SAUDE E MATERNIDADE SA",
  prestEndereco: "DOUTOR MARIO VIANA",
  prestNumero: "653",
  prestComplemento: "",
  prestBairro: "SANTA ROSA",
  prestCEP: "",
  telefone1: "",
  telefone2: "",
  telefone3: "",
},{
  prestNome: "CC DIADEMA",
  prestEndereco: "AV. FABIO EDUARDO RAMOS ESQUIVEL",
  prestNumero: "2421",
  prestComplemento: "",
  prestBairro: "CANHEMA",
  prestCEP: "09941201",
  telefone1: "1140901740",
  telefone2: "",
  telefone3: "",
},{
  prestNome: "CENTRO CLINICO JUNDIAI",
  prestEndereco: "R. SAO BENTO",
  prestNumero: "41",
  prestComplemento: "",
  prestBairro: "CENTRO",
  prestCEP: "",
  telefone1: "1140901740",
  telefone2: "31552000",
  telefone3: "",
},{
  prestNome: "CENTRO CLINICO ALPHAVILLE",
  prestEndereco: "AL. AMAZONAS",
  prestNumero: "329",
  prestComplemento: "ALPHAVILLE CENTRO INDUSTRIAL E",
  prestBairro: "",
  prestCEP: "06454070",
  telefone1: "1140901740",
  telefone2: "",
  telefone3: "",
},


];

// Função GET com suporte a pesquisa
export async function GET(req: Request) {
  const { searchParams } = new URL(req.url);
  const query = searchParams.get("q")?.toLowerCase() || "";

  // Filtrando prestadores pelo nome
  const filteredPrestadores = prestadores.filter((prestador) =>
    prestador.prestNome.toLowerCase().includes(query)
  );

  return NextResponse.json(filteredPrestadores);
}
